
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO PUBLIC;


GO
GRANT SELECT, INSERT, UPDATE ON dbo.Buildings TO PUBLIC;

GO
GRANT SELECT, INSERT, UPDATE ON dbo.Users TO PUBLIC;

GO
GRANT SELECT, INSERT, UPDATE ON dbo.Rooms TO PUBLIC;

GO
GRANT SELECT, INSERT, UPDATE ON dbo.Requests TO PUBLIC;

GO
GRANT SELECT, INSERT, UPDATE ON dbo.Equipments TO PUBLIC;

GO
GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO PUBLIC;

